// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ComplexImport.proto

package test.complex;

public final class ComplexImport {
  private ComplexImport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.complex.Complex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.test.simple.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.test.simple.Type type = 3;</code>
     * @return The type.
     */
    test.simple.SimpleEnum.Type getType();

    /**
     * <code>.test.simple.Msg msg = 4;</code>
     * @return Whether the msg field is set.
     */
    boolean hasMsg();
    /**
     * <code>.test.simple.Msg msg = 4;</code>
     * @return The msg.
     */
    test.simple.SimpleEnum.Msg getMsg();
    /**
     * <code>.test.simple.Msg msg = 4;</code>
     */
    test.simple.SimpleEnum.MsgOrBuilder getMsgOrBuilder();
  }
  /**
   * Protobuf type {@code test.complex.Complex}
   */
  public static final class Complex extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.complex.Complex)
      ComplexOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Complex.newBuilder() to construct.
    private Complex(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Complex() {
      content_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Complex();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Complex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 34: {
              test.simple.SimpleEnum.Msg.Builder subBuilder = null;
              if (msg_ != null) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(test.simple.SimpleEnum.Msg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.complex.ComplexImport.internal_static_test_complex_Complex_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.complex.ComplexImport.internal_static_test_complex_Complex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.complex.ComplexImport.Complex.class, test.complex.ComplexImport.Complex.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.test.simple.Type type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.test.simple.Type type = 3;</code>
     * @return The type.
     */
    @java.lang.Override public test.simple.SimpleEnum.Type getType() {
      @SuppressWarnings("deprecation")
      test.simple.SimpleEnum.Type result = test.simple.SimpleEnum.Type.valueOf(type_);
      return result == null ? test.simple.SimpleEnum.Type.UNRECOGNIZED : result;
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private test.simple.SimpleEnum.Msg msg_;
    /**
     * <code>.test.simple.Msg msg = 4;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return msg_ != null;
    }
    /**
     * <code>.test.simple.Msg msg = 4;</code>
     * @return The msg.
     */
    @java.lang.Override
    public test.simple.SimpleEnum.Msg getMsg() {
      return msg_ == null ? test.simple.SimpleEnum.Msg.getDefaultInstance() : msg_;
    }
    /**
     * <code>.test.simple.Msg msg = 4;</code>
     */
    @java.lang.Override
    public test.simple.SimpleEnum.MsgOrBuilder getMsgOrBuilder() {
      return getMsg();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (type_ != test.simple.SimpleEnum.Type.ERROR.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (msg_ != null) {
        output.writeMessage(4, getMsg());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (type_ != test.simple.SimpleEnum.Type.ERROR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (msg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMsg());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.complex.ComplexImport.Complex)) {
        return super.equals(obj);
      }
      test.complex.ComplexImport.Complex other = (test.complex.ComplexImport.Complex) obj;

      if (getId()
          != other.getId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (type_ != other.type_) return false;
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.complex.ComplexImport.Complex parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.complex.ComplexImport.Complex parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.complex.ComplexImport.Complex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.complex.ComplexImport.Complex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.complex.ComplexImport.Complex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.complex.ComplexImport.Complex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.complex.ComplexImport.Complex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.complex.ComplexImport.Complex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.complex.ComplexImport.Complex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.complex.ComplexImport.Complex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.complex.ComplexImport.Complex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.complex.ComplexImport.Complex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.complex.ComplexImport.Complex prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.complex.Complex}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.complex.Complex)
        test.complex.ComplexImport.ComplexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.complex.ComplexImport.internal_static_test_complex_Complex_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.complex.ComplexImport.internal_static_test_complex_Complex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.complex.ComplexImport.Complex.class, test.complex.ComplexImport.Complex.Builder.class);
      }

      // Construct using test.complex.ComplexImport.Complex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        content_ = "";

        type_ = 0;

        if (msgBuilder_ == null) {
          msg_ = null;
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.complex.ComplexImport.internal_static_test_complex_Complex_descriptor;
      }

      @java.lang.Override
      public test.complex.ComplexImport.Complex getDefaultInstanceForType() {
        return test.complex.ComplexImport.Complex.getDefaultInstance();
      }

      @java.lang.Override
      public test.complex.ComplexImport.Complex build() {
        test.complex.ComplexImport.Complex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.complex.ComplexImport.Complex buildPartial() {
        test.complex.ComplexImport.Complex result = new test.complex.ComplexImport.Complex(this);
        result.id_ = id_;
        result.content_ = content_;
        result.type_ = type_;
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.complex.ComplexImport.Complex) {
          return mergeFrom((test.complex.ComplexImport.Complex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.complex.ComplexImport.Complex other) {
        if (other == test.complex.ComplexImport.Complex.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.complex.ComplexImport.Complex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.complex.ComplexImport.Complex) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.test.simple.Type type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.test.simple.Type type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.test.simple.Type type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public test.simple.SimpleEnum.Type getType() {
        @SuppressWarnings("deprecation")
        test.simple.SimpleEnum.Type result = test.simple.SimpleEnum.Type.valueOf(type_);
        return result == null ? test.simple.SimpleEnum.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.test.simple.Type type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(test.simple.SimpleEnum.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.test.simple.Type type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private test.simple.SimpleEnum.Msg msg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          test.simple.SimpleEnum.Msg, test.simple.SimpleEnum.Msg.Builder, test.simple.SimpleEnum.MsgOrBuilder> msgBuilder_;
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       * @return Whether the msg field is set.
       */
      public boolean hasMsg() {
        return msgBuilder_ != null || msg_ != null;
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       * @return The msg.
       */
      public test.simple.SimpleEnum.Msg getMsg() {
        if (msgBuilder_ == null) {
          return msg_ == null ? test.simple.SimpleEnum.Msg.getDefaultInstance() : msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       */
      public Builder setMsg(test.simple.SimpleEnum.Msg value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       */
      public Builder setMsg(
          test.simple.SimpleEnum.Msg.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       */
      public Builder mergeMsg(test.simple.SimpleEnum.Msg value) {
        if (msgBuilder_ == null) {
          if (msg_ != null) {
            msg_ =
              test.simple.SimpleEnum.Msg.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = null;
          onChanged();
        } else {
          msg_ = null;
          msgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       */
      public test.simple.SimpleEnum.Msg.Builder getMsgBuilder() {
        
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       */
      public test.simple.SimpleEnum.MsgOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_ == null ?
              test.simple.SimpleEnum.Msg.getDefaultInstance() : msg_;
        }
      }
      /**
       * <code>.test.simple.Msg msg = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          test.simple.SimpleEnum.Msg, test.simple.SimpleEnum.Msg.Builder, test.simple.SimpleEnum.MsgOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              test.simple.SimpleEnum.Msg, test.simple.SimpleEnum.Msg.Builder, test.simple.SimpleEnum.MsgOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.complex.Complex)
    }

    // @@protoc_insertion_point(class_scope:test.complex.Complex)
    private static final test.complex.ComplexImport.Complex DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.complex.ComplexImport.Complex();
    }

    public static test.complex.ComplexImport.Complex getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Complex>
        PARSER = new com.google.protobuf.AbstractParser<Complex>() {
      @java.lang.Override
      public Complex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Complex(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Complex> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Complex> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.complex.ComplexImport.Complex getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_complex_Complex_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_complex_Complex_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/ComplexImport.proto\022\014test.comple" +
      "x\032\026proto/SimpleEnum.proto\"f\n\007Complex\022\n\n\002" +
      "id\030\001 \001(\r\022\017\n\007content\030\002 \001(\t\022\037\n\004type\030\003 \001(\0162" +
      "\021.test.simple.Type\022\035\n\003msg\030\004 \001(\0132\020.test.s" +
      "imple.MsgB\035\n\014test.complexB\rComplexImport" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          test.simple.SimpleEnum.getDescriptor(),
        });
    internal_static_test_complex_Complex_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_complex_Complex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_complex_Complex_descriptor,
        new java.lang.String[] { "Id", "Content", "Type", "Msg", });
    test.simple.SimpleEnum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
