// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/VersionCompMsg.proto

package test.simple;

public final class VersionCompMsg {
  private VersionCompMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CompMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string str03 = 3;</code>
     * @return Whether the str03 field is set.
     */
    boolean hasStr03();
    /**
     * <code>optional string str03 = 3;</code>
     * @return The str03.
     */
    java.lang.String getStr03();
    /**
     * <code>optional string str03 = 3;</code>
     * @return The bytes for str03.
     */
    com.google.protobuf.ByteString
        getStr03Bytes();

    /**
     * <code>optional string str04 = 4;</code>
     * @return Whether the str04 field is set.
     */
    boolean hasStr04();
    /**
     * <code>optional string str04 = 4;</code>
     * @return The str04.
     */
    java.lang.String getStr04();
    /**
     * <code>optional string str04 = 4;</code>
     * @return The bytes for str04.
     */
    com.google.protobuf.ByteString
        getStr04Bytes();

    /**
     * <code>optional string str05 = 5;</code>
     * @return Whether the str05 field is set.
     */
    boolean hasStr05();
    /**
     * <code>optional string str05 = 5;</code>
     * @return The str05.
     */
    java.lang.String getStr05();
    /**
     * <code>optional string str05 = 5;</code>
     * @return The bytes for str05.
     */
    com.google.protobuf.ByteString
        getStr05Bytes();

    /**
     * <code>optional string str06 = 6;</code>
     * @return Whether the str06 field is set.
     */
    boolean hasStr06();
    /**
     * <code>optional string str06 = 6;</code>
     * @return The str06.
     */
    java.lang.String getStr06();
    /**
     * <code>optional string str06 = 6;</code>
     * @return The bytes for str06.
     */
    com.google.protobuf.ByteString
        getStr06Bytes();

    /**
     * <code>optional string str07 = 7;</code>
     * @return Whether the str07 field is set.
     */
    boolean hasStr07();
    /**
     * <code>optional string str07 = 7;</code>
     * @return The str07.
     */
    java.lang.String getStr07();
    /**
     * <code>optional string str07 = 7;</code>
     * @return The bytes for str07.
     */
    com.google.protobuf.ByteString
        getStr07Bytes();

    /**
     * <code>optional string str08 = 8;</code>
     * @return Whether the str08 field is set.
     */
    boolean hasStr08();
    /**
     * <code>optional string str08 = 8;</code>
     * @return The str08.
     */
    java.lang.String getStr08();
    /**
     * <code>optional string str08 = 8;</code>
     * @return The bytes for str08.
     */
    com.google.protobuf.ByteString
        getStr08Bytes();

    /**
     * <code>optional string str09 = 9;</code>
     * @return Whether the str09 field is set.
     */
    boolean hasStr09();
    /**
     * <code>optional string str09 = 9;</code>
     * @return The str09.
     */
    java.lang.String getStr09();
    /**
     * <code>optional string str09 = 9;</code>
     * @return The bytes for str09.
     */
    com.google.protobuf.ByteString
        getStr09Bytes();

    /**
     * <code>optional string str99 = 99;</code>
     * @return Whether the str99 field is set.
     */
    boolean hasStr99();
    /**
     * <code>optional string str99 = 99;</code>
     * @return The str99.
     */
    java.lang.String getStr99();
    /**
     * <code>optional string str99 = 99;</code>
     * @return The bytes for str99.
     */
    com.google.protobuf.ByteString
        getStr99Bytes();
  }
  /**
   * <pre>
   * [开始 消息定义]
   * </pre>
   *
   * Protobuf type {@code CompMsg}
   */
  public static final class CompMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CompMsg)
      CompMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CompMsg.newBuilder() to construct.
    private CompMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompMsg() {
      name_ = "";
      str03_ = "";
      str04_ = "";
      str05_ = "";
      str06_ = "";
      str07_ = "";
      str08_ = "";
      str09_ = "";
      str99_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CompMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CompMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              str03_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              str04_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              str05_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              str06_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              str07_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              str08_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              str09_ = s;
              break;
            }
            case 794: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              str99_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.simple.VersionCompMsg.internal_static_CompMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.simple.VersionCompMsg.internal_static_CompMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.simple.VersionCompMsg.CompMsg.class, test.simple.VersionCompMsg.CompMsg.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR03_FIELD_NUMBER = 3;
    private volatile java.lang.Object str03_;
    /**
     * <code>optional string str03 = 3;</code>
     * @return Whether the str03 field is set.
     */
    @java.lang.Override
    public boolean hasStr03() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string str03 = 3;</code>
     * @return The str03.
     */
    @java.lang.Override
    public java.lang.String getStr03() {
      java.lang.Object ref = str03_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str03_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str03 = 3;</code>
     * @return The bytes for str03.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr03Bytes() {
      java.lang.Object ref = str03_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str03_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR04_FIELD_NUMBER = 4;
    private volatile java.lang.Object str04_;
    /**
     * <code>optional string str04 = 4;</code>
     * @return Whether the str04 field is set.
     */
    @java.lang.Override
    public boolean hasStr04() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string str04 = 4;</code>
     * @return The str04.
     */
    @java.lang.Override
    public java.lang.String getStr04() {
      java.lang.Object ref = str04_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str04_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str04 = 4;</code>
     * @return The bytes for str04.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr04Bytes() {
      java.lang.Object ref = str04_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str04_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR05_FIELD_NUMBER = 5;
    private volatile java.lang.Object str05_;
    /**
     * <code>optional string str05 = 5;</code>
     * @return Whether the str05 field is set.
     */
    @java.lang.Override
    public boolean hasStr05() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string str05 = 5;</code>
     * @return The str05.
     */
    @java.lang.Override
    public java.lang.String getStr05() {
      java.lang.Object ref = str05_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str05_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str05 = 5;</code>
     * @return The bytes for str05.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr05Bytes() {
      java.lang.Object ref = str05_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str05_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR06_FIELD_NUMBER = 6;
    private volatile java.lang.Object str06_;
    /**
     * <code>optional string str06 = 6;</code>
     * @return Whether the str06 field is set.
     */
    @java.lang.Override
    public boolean hasStr06() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string str06 = 6;</code>
     * @return The str06.
     */
    @java.lang.Override
    public java.lang.String getStr06() {
      java.lang.Object ref = str06_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str06_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str06 = 6;</code>
     * @return The bytes for str06.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr06Bytes() {
      java.lang.Object ref = str06_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str06_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR07_FIELD_NUMBER = 7;
    private volatile java.lang.Object str07_;
    /**
     * <code>optional string str07 = 7;</code>
     * @return Whether the str07 field is set.
     */
    @java.lang.Override
    public boolean hasStr07() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string str07 = 7;</code>
     * @return The str07.
     */
    @java.lang.Override
    public java.lang.String getStr07() {
      java.lang.Object ref = str07_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str07_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str07 = 7;</code>
     * @return The bytes for str07.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr07Bytes() {
      java.lang.Object ref = str07_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str07_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR08_FIELD_NUMBER = 8;
    private volatile java.lang.Object str08_;
    /**
     * <code>optional string str08 = 8;</code>
     * @return Whether the str08 field is set.
     */
    @java.lang.Override
    public boolean hasStr08() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string str08 = 8;</code>
     * @return The str08.
     */
    @java.lang.Override
    public java.lang.String getStr08() {
      java.lang.Object ref = str08_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str08_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str08 = 8;</code>
     * @return The bytes for str08.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr08Bytes() {
      java.lang.Object ref = str08_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str08_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR09_FIELD_NUMBER = 9;
    private volatile java.lang.Object str09_;
    /**
     * <code>optional string str09 = 9;</code>
     * @return Whether the str09 field is set.
     */
    @java.lang.Override
    public boolean hasStr09() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string str09 = 9;</code>
     * @return The str09.
     */
    @java.lang.Override
    public java.lang.String getStr09() {
      java.lang.Object ref = str09_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str09_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str09 = 9;</code>
     * @return The bytes for str09.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr09Bytes() {
      java.lang.Object ref = str09_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str09_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR99_FIELD_NUMBER = 99;
    private volatile java.lang.Object str99_;
    /**
     * <code>optional string str99 = 99;</code>
     * @return Whether the str99 field is set.
     */
    @java.lang.Override
    public boolean hasStr99() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string str99 = 99;</code>
     * @return The str99.
     */
    @java.lang.Override
    public java.lang.String getStr99() {
      java.lang.Object ref = str99_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str99_ = s;
        return s;
      }
    }
    /**
     * <code>optional string str99 = 99;</code>
     * @return The bytes for str99.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStr99Bytes() {
      java.lang.Object ref = str99_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str99_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, str03_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, str04_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, str05_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, str06_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, str07_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, str08_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, str09_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 99, str99_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, str03_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, str04_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, str05_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, str06_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, str07_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, str08_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, str09_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(99, str99_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof test.simple.VersionCompMsg.CompMsg)) {
        return super.equals(obj);
      }
      test.simple.VersionCompMsg.CompMsg other = (test.simple.VersionCompMsg.CompMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasStr03() != other.hasStr03()) return false;
      if (hasStr03()) {
        if (!getStr03()
            .equals(other.getStr03())) return false;
      }
      if (hasStr04() != other.hasStr04()) return false;
      if (hasStr04()) {
        if (!getStr04()
            .equals(other.getStr04())) return false;
      }
      if (hasStr05() != other.hasStr05()) return false;
      if (hasStr05()) {
        if (!getStr05()
            .equals(other.getStr05())) return false;
      }
      if (hasStr06() != other.hasStr06()) return false;
      if (hasStr06()) {
        if (!getStr06()
            .equals(other.getStr06())) return false;
      }
      if (hasStr07() != other.hasStr07()) return false;
      if (hasStr07()) {
        if (!getStr07()
            .equals(other.getStr07())) return false;
      }
      if (hasStr08() != other.hasStr08()) return false;
      if (hasStr08()) {
        if (!getStr08()
            .equals(other.getStr08())) return false;
      }
      if (hasStr09() != other.hasStr09()) return false;
      if (hasStr09()) {
        if (!getStr09()
            .equals(other.getStr09())) return false;
      }
      if (hasStr99() != other.hasStr99()) return false;
      if (hasStr99()) {
        if (!getStr99()
            .equals(other.getStr99())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasStr03()) {
        hash = (37 * hash) + STR03_FIELD_NUMBER;
        hash = (53 * hash) + getStr03().hashCode();
      }
      if (hasStr04()) {
        hash = (37 * hash) + STR04_FIELD_NUMBER;
        hash = (53 * hash) + getStr04().hashCode();
      }
      if (hasStr05()) {
        hash = (37 * hash) + STR05_FIELD_NUMBER;
        hash = (53 * hash) + getStr05().hashCode();
      }
      if (hasStr06()) {
        hash = (37 * hash) + STR06_FIELD_NUMBER;
        hash = (53 * hash) + getStr06().hashCode();
      }
      if (hasStr07()) {
        hash = (37 * hash) + STR07_FIELD_NUMBER;
        hash = (53 * hash) + getStr07().hashCode();
      }
      if (hasStr08()) {
        hash = (37 * hash) + STR08_FIELD_NUMBER;
        hash = (53 * hash) + getStr08().hashCode();
      }
      if (hasStr09()) {
        hash = (37 * hash) + STR09_FIELD_NUMBER;
        hash = (53 * hash) + getStr09().hashCode();
      }
      if (hasStr99()) {
        hash = (37 * hash) + STR99_FIELD_NUMBER;
        hash = (53 * hash) + getStr99().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.simple.VersionCompMsg.CompMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static test.simple.VersionCompMsg.CompMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static test.simple.VersionCompMsg.CompMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(test.simple.VersionCompMsg.CompMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [开始 消息定义]
     * </pre>
     *
     * Protobuf type {@code CompMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CompMsg)
        test.simple.VersionCompMsg.CompMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.simple.VersionCompMsg.internal_static_CompMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.simple.VersionCompMsg.internal_static_CompMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.simple.VersionCompMsg.CompMsg.class, test.simple.VersionCompMsg.CompMsg.Builder.class);
      }

      // Construct using test.simple.VersionCompMsg.CompMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        str03_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        str04_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        str05_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        str06_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        str07_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        str08_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        str09_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        str99_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.simple.VersionCompMsg.internal_static_CompMsg_descriptor;
      }

      @java.lang.Override
      public test.simple.VersionCompMsg.CompMsg getDefaultInstanceForType() {
        return test.simple.VersionCompMsg.CompMsg.getDefaultInstance();
      }

      @java.lang.Override
      public test.simple.VersionCompMsg.CompMsg build() {
        test.simple.VersionCompMsg.CompMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public test.simple.VersionCompMsg.CompMsg buildPartial() {
        test.simple.VersionCompMsg.CompMsg result = new test.simple.VersionCompMsg.CompMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.str03_ = str03_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.str04_ = str04_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.str05_ = str05_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.str06_ = str06_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.str07_ = str07_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.str08_ = str08_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.str09_ = str09_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.str99_ = str99_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.simple.VersionCompMsg.CompMsg) {
          return mergeFrom((test.simple.VersionCompMsg.CompMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.simple.VersionCompMsg.CompMsg other) {
        if (other == test.simple.VersionCompMsg.CompMsg.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasStr03()) {
          bitField0_ |= 0x00000001;
          str03_ = other.str03_;
          onChanged();
        }
        if (other.hasStr04()) {
          bitField0_ |= 0x00000002;
          str04_ = other.str04_;
          onChanged();
        }
        if (other.hasStr05()) {
          bitField0_ |= 0x00000004;
          str05_ = other.str05_;
          onChanged();
        }
        if (other.hasStr06()) {
          bitField0_ |= 0x00000008;
          str06_ = other.str06_;
          onChanged();
        }
        if (other.hasStr07()) {
          bitField0_ |= 0x00000010;
          str07_ = other.str07_;
          onChanged();
        }
        if (other.hasStr08()) {
          bitField0_ |= 0x00000020;
          str08_ = other.str08_;
          onChanged();
        }
        if (other.hasStr09()) {
          bitField0_ |= 0x00000040;
          str09_ = other.str09_;
          onChanged();
        }
        if (other.hasStr99()) {
          bitField0_ |= 0x00000080;
          str99_ = other.str99_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.simple.VersionCompMsg.CompMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.simple.VersionCompMsg.CompMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str03_ = "";
      /**
       * <code>optional string str03 = 3;</code>
       * @return Whether the str03 field is set.
       */
      public boolean hasStr03() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string str03 = 3;</code>
       * @return The str03.
       */
      public java.lang.String getStr03() {
        java.lang.Object ref = str03_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str03_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str03 = 3;</code>
       * @return The bytes for str03.
       */
      public com.google.protobuf.ByteString
          getStr03Bytes() {
        java.lang.Object ref = str03_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str03_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str03 = 3;</code>
       * @param value The str03 to set.
       * @return This builder for chaining.
       */
      public Builder setStr03(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        str03_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str03 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr03() {
        bitField0_ = (bitField0_ & ~0x00000001);
        str03_ = getDefaultInstance().getStr03();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str03 = 3;</code>
       * @param value The bytes for str03 to set.
       * @return This builder for chaining.
       */
      public Builder setStr03Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        str03_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str04_ = "";
      /**
       * <code>optional string str04 = 4;</code>
       * @return Whether the str04 field is set.
       */
      public boolean hasStr04() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string str04 = 4;</code>
       * @return The str04.
       */
      public java.lang.String getStr04() {
        java.lang.Object ref = str04_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str04_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str04 = 4;</code>
       * @return The bytes for str04.
       */
      public com.google.protobuf.ByteString
          getStr04Bytes() {
        java.lang.Object ref = str04_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str04_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str04 = 4;</code>
       * @param value The str04 to set.
       * @return This builder for chaining.
       */
      public Builder setStr04(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        str04_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str04 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr04() {
        bitField0_ = (bitField0_ & ~0x00000002);
        str04_ = getDefaultInstance().getStr04();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str04 = 4;</code>
       * @param value The bytes for str04 to set.
       * @return This builder for chaining.
       */
      public Builder setStr04Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        str04_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str05_ = "";
      /**
       * <code>optional string str05 = 5;</code>
       * @return Whether the str05 field is set.
       */
      public boolean hasStr05() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string str05 = 5;</code>
       * @return The str05.
       */
      public java.lang.String getStr05() {
        java.lang.Object ref = str05_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str05_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str05 = 5;</code>
       * @return The bytes for str05.
       */
      public com.google.protobuf.ByteString
          getStr05Bytes() {
        java.lang.Object ref = str05_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str05_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str05 = 5;</code>
       * @param value The str05 to set.
       * @return This builder for chaining.
       */
      public Builder setStr05(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        str05_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str05 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr05() {
        bitField0_ = (bitField0_ & ~0x00000004);
        str05_ = getDefaultInstance().getStr05();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str05 = 5;</code>
       * @param value The bytes for str05 to set.
       * @return This builder for chaining.
       */
      public Builder setStr05Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        str05_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str06_ = "";
      /**
       * <code>optional string str06 = 6;</code>
       * @return Whether the str06 field is set.
       */
      public boolean hasStr06() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string str06 = 6;</code>
       * @return The str06.
       */
      public java.lang.String getStr06() {
        java.lang.Object ref = str06_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str06_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str06 = 6;</code>
       * @return The bytes for str06.
       */
      public com.google.protobuf.ByteString
          getStr06Bytes() {
        java.lang.Object ref = str06_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str06_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str06 = 6;</code>
       * @param value The str06 to set.
       * @return This builder for chaining.
       */
      public Builder setStr06(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        str06_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str06 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr06() {
        bitField0_ = (bitField0_ & ~0x00000008);
        str06_ = getDefaultInstance().getStr06();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str06 = 6;</code>
       * @param value The bytes for str06 to set.
       * @return This builder for chaining.
       */
      public Builder setStr06Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        str06_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str07_ = "";
      /**
       * <code>optional string str07 = 7;</code>
       * @return Whether the str07 field is set.
       */
      public boolean hasStr07() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string str07 = 7;</code>
       * @return The str07.
       */
      public java.lang.String getStr07() {
        java.lang.Object ref = str07_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str07_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str07 = 7;</code>
       * @return The bytes for str07.
       */
      public com.google.protobuf.ByteString
          getStr07Bytes() {
        java.lang.Object ref = str07_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str07_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str07 = 7;</code>
       * @param value The str07 to set.
       * @return This builder for chaining.
       */
      public Builder setStr07(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        str07_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str07 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr07() {
        bitField0_ = (bitField0_ & ~0x00000010);
        str07_ = getDefaultInstance().getStr07();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str07 = 7;</code>
       * @param value The bytes for str07 to set.
       * @return This builder for chaining.
       */
      public Builder setStr07Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000010;
        str07_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str08_ = "";
      /**
       * <code>optional string str08 = 8;</code>
       * @return Whether the str08 field is set.
       */
      public boolean hasStr08() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string str08 = 8;</code>
       * @return The str08.
       */
      public java.lang.String getStr08() {
        java.lang.Object ref = str08_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str08_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str08 = 8;</code>
       * @return The bytes for str08.
       */
      public com.google.protobuf.ByteString
          getStr08Bytes() {
        java.lang.Object ref = str08_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str08_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str08 = 8;</code>
       * @param value The str08 to set.
       * @return This builder for chaining.
       */
      public Builder setStr08(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        str08_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str08 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr08() {
        bitField0_ = (bitField0_ & ~0x00000020);
        str08_ = getDefaultInstance().getStr08();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str08 = 8;</code>
       * @param value The bytes for str08 to set.
       * @return This builder for chaining.
       */
      public Builder setStr08Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000020;
        str08_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str09_ = "";
      /**
       * <code>optional string str09 = 9;</code>
       * @return Whether the str09 field is set.
       */
      public boolean hasStr09() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string str09 = 9;</code>
       * @return The str09.
       */
      public java.lang.String getStr09() {
        java.lang.Object ref = str09_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str09_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str09 = 9;</code>
       * @return The bytes for str09.
       */
      public com.google.protobuf.ByteString
          getStr09Bytes() {
        java.lang.Object ref = str09_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str09_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str09 = 9;</code>
       * @param value The str09 to set.
       * @return This builder for chaining.
       */
      public Builder setStr09(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        str09_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str09 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr09() {
        bitField0_ = (bitField0_ & ~0x00000040);
        str09_ = getDefaultInstance().getStr09();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str09 = 9;</code>
       * @param value The bytes for str09 to set.
       * @return This builder for chaining.
       */
      public Builder setStr09Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000040;
        str09_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str99_ = "";
      /**
       * <code>optional string str99 = 99;</code>
       * @return Whether the str99 field is set.
       */
      public boolean hasStr99() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string str99 = 99;</code>
       * @return The str99.
       */
      public java.lang.String getStr99() {
        java.lang.Object ref = str99_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str99_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str99 = 99;</code>
       * @return The bytes for str99.
       */
      public com.google.protobuf.ByteString
          getStr99Bytes() {
        java.lang.Object ref = str99_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str99_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str99 = 99;</code>
       * @param value The str99 to set.
       * @return This builder for chaining.
       */
      public Builder setStr99(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        str99_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str99 = 99;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr99() {
        bitField0_ = (bitField0_ & ~0x00000080);
        str99_ = getDefaultInstance().getStr99();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str99 = 99;</code>
       * @param value The bytes for str99 to set.
       * @return This builder for chaining.
       */
      public Builder setStr99Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000080;
        str99_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CompMsg)
    }

    // @@protoc_insertion_point(class_scope:CompMsg)
    private static final test.simple.VersionCompMsg.CompMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new test.simple.VersionCompMsg.CompMsg();
    }

    public static test.simple.VersionCompMsg.CompMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompMsg>
        PARSER = new com.google.protobuf.AbstractParser<CompMsg>() {
      @java.lang.Override
      public CompMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public test.simple.VersionCompMsg.CompMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CompMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CompMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/VersionCompMsg.proto\"\223\002\n\007CompMsg" +
      "\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\022\022\n\005str03\030\003 \001(" +
      "\tH\000\210\001\001\022\022\n\005str04\030\004 \001(\tH\001\210\001\001\022\022\n\005str05\030\005 \001(" +
      "\tH\002\210\001\001\022\022\n\005str06\030\006 \001(\tH\003\210\001\001\022\022\n\005str07\030\007 \001(" +
      "\tH\004\210\001\001\022\022\n\005str08\030\010 \001(\tH\005\210\001\001\022\022\n\005str09\030\t \001(" +
      "\tH\006\210\001\001\022\022\n\005str99\030c \001(\tH\007\210\001\001B\010\n\006_str03B\010\n\006" +
      "_str04B\010\n\006_str05B\010\n\006_str06B\010\n\006_str07B\010\n\006" +
      "_str08B\010\n\006_str09B\010\n\006_str99B\035\n\013test.simpl" +
      "eB\016VersionCompMsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CompMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CompMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CompMsg_descriptor,
        new java.lang.String[] { "Id", "Name", "Str03", "Str04", "Str05", "Str06", "Str07", "Str08", "Str09", "Str99", "Str03", "Str04", "Str05", "Str06", "Str07", "Str08", "Str09", "Str99", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
