package cn.zxf.assertj;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link TestUser} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractTestUserAssert<S extends AbstractTestUserAssert<S, A>, A extends TestUser> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractTestUserAssert}</code> to make assertions on actual TestUser.
   * @param actual the TestUser we want to make assertions on.
   */
  protected AbstractTestUserAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
