// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SimpleMulti.proto

package test.simple.multi;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.simple.multi.Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>.test.simple.multi.Type type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.test.simple.multi.Type type = 3;</code>
   * @return The type.
   */
  test.simple.multi.Type getType();
}
