// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SimpleMulti.proto

package test.simple.multi;

public final class SimpleMulti {
  private SimpleMulti() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_simple_multi_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_simple_multi_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027proto/SimpleMulti.proto\022\021test.simple.m" +
      "ulti\"I\n\003Msg\022\n\n\002id\030\001 \001(\r\022\017\n\007content\030\002 \001(\t" +
      "\022%\n\004type\030\003 \001(\0162\027.test.simple.multi.Type*" +
      "a\n\004Type\022\t\n\005ERROR\020\000\022\021\n\rLOGIN_REQUEST\020\001\022\022\n" +
      "\016LOGIN_RESPONSE\020\002\022\022\n\016LOGOUT_REQUEST\020\003\022\023\n" +
      "\017LOGOUT_RESPONSE\020\004B\025\n\021test.simple.multiP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_simple_multi_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_simple_multi_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_simple_multi_Msg_descriptor,
        new java.lang.String[] { "Id", "Content", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
