// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SimpleMulti.proto

package test.simple.multi;

/**
 * Protobuf enum {@code test.simple.multi.Type}
 */
public enum Type
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ERROR = 0;</code>
   */
  ERROR(0),
  /**
   * <pre>
   * 登陆请求
   * </pre>
   *
   * <code>LOGIN_REQUEST = 1;</code>
   */
  LOGIN_REQUEST(1),
  /**
   * <pre>
   * 登录响应
   * </pre>
   *
   * <code>LOGIN_RESPONSE = 2;</code>
   */
  LOGIN_RESPONSE(2),
  /**
   * <pre>
   * 退出请求
   * </pre>
   *
   * <code>LOGOUT_REQUEST = 3;</code>
   */
  LOGOUT_REQUEST(3),
  /**
   * <code>LOGOUT_RESPONSE = 4;</code>
   */
  LOGOUT_RESPONSE(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ERROR = 0;</code>
   */
  public static final int ERROR_VALUE = 0;
  /**
   * <pre>
   * 登陆请求
   * </pre>
   *
   * <code>LOGIN_REQUEST = 1;</code>
   */
  public static final int LOGIN_REQUEST_VALUE = 1;
  /**
   * <pre>
   * 登录响应
   * </pre>
   *
   * <code>LOGIN_RESPONSE = 2;</code>
   */
  public static final int LOGIN_RESPONSE_VALUE = 2;
  /**
   * <pre>
   * 退出请求
   * </pre>
   *
   * <code>LOGOUT_REQUEST = 3;</code>
   */
  public static final int LOGOUT_REQUEST_VALUE = 3;
  /**
   * <code>LOGOUT_RESPONSE = 4;</code>
   */
  public static final int LOGOUT_RESPONSE_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Type valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Type forNumber(int value) {
    switch (value) {
      case 0: return ERROR;
      case 1: return LOGIN_REQUEST;
      case 2: return LOGIN_RESPONSE;
      case 3: return LOGOUT_REQUEST;
      case 4: return LOGOUT_RESPONSE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Type>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Type> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Type>() {
          public Type findValueByNumber(int number) {
            return Type.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return test.simple.multi.SimpleMulti.getDescriptor().getEnumTypes().get(0);
  }

  private static final Type[] VALUES = values();

  public static Type valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Type(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:test.simple.multi.Type)
}

